name: buildWithArtifacts

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'shopwareUploader.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'shopwareUploader'
